language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false  -DWITH_CAIRO=false -DWITH_MAGICK=false -DWITH_GMP=false" 
  - BTYPE="-DCMAKE_BUILD_TYPE=Release" 
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug" 

before_script:



matrix:
  exclude:
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false  -DWITH_CAIRO=false -DWITH_MAGICK=false -DWITH_GMP=false" 
 

script: 
  - cmake . $BTYPE
  - make


after_script: 
  - "make test"
